openapi: 3.0.4
info:
  title: iTrade API - Portfolio API
  description: |-
    Account Summary
    Trust Balance
    Trust Movement
    Custody
    Collateral Financing
    Contra
    Contracts
  version: 0.0.1
servers:
  - url: http://localhost:8080/portal/portfolio/api/v1
paths:
  /accountSummary:
    get:
      summary: Get all account information
      operationId: getAccountSummary
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountSummary'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /trustBalance:
    get:
      summary: Get all account trust balance summary
      operationId: getTrustBalance
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrustBalances'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /trustBalance/{accountNo}/details/{currency}:
    get:
      summary: Get trust balance detail by account no & currency
      operationId: getTrustBalanceDetails
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
        - name: currency
          in: path
          description: currency
          required: true
          schema:
            type: string
            example: 'SGD'
        - name: pageSize
          in: query
          description: page size
          required: false
          schema:
            type: number
            format: int32
        - name: pageIndex
          in: query
          description: page index
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  trustBalances:
                    type: array
                    items:
                      $ref: '#/components/schemas/TrustBalances'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /custody/{accountNo}:
    get:
      summary: Get custody holding by account No
      operationId: getCustodyByAccountNo
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
        - name: pageSize
          in: query
          description: page size
          required: false
          schema:
            type: number
            format: int32
        - name: pageIndex
          in: query
          description: page index
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  trustBalances:
                    type: array
                    items:
                      $ref: '#/components/schemas/Custody'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /margin/{accountNo}:
    get:
      summary: Get collateral financing summary by account No
      operationId: getCollateralFinancingByAccountNo
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/CollateralFinancing'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /margin/{accountNo}/details:
    get:
      summary: Get collateral financing detail by account no & currency
      operationId: getCollateralFinancingDetailByAccountNo
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
        - name: pageSize
          in: query
          description: page size
          required: false
          schema:
            type: number
            format: int32
        - name: pageIndex
          in: query
          description: page index
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  collateralFinancingDetails:
                    type: array
                    items:
                      $ref: '#/components/schemas/CollateralFinancingDetail'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /contracts/{accountNo}:
    get:
      summary: Get contracts by account no
      operationId: getContractsByAccountNo
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
        - name: marketCode
          in: query
          description: market Code
          required: false
          schema:
            type: string
        - name: pageSize
          in: query
          description: page size
          required: false
          schema:
            type: number
            format: int32
        - name: pageIndex
          in: query
          description: page index
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  contracts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contract'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /contracts/{accountNo}/pastdue:
    get:
      summary: Get contracts past due (share awaiting) by account no
      operationId: getShareAwaitingByAccountNo
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
        - name: marketCode
          in: query
          description: market Code
          required: false
          schema:
            type: string
        - name: pageSize
          in: query
          description: page size
          required: false
          schema:
            type: number
            format: int32
        - name: pageIndex
          in: query
          description: page index
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  pastDue:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contract'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /contra/{accountNo}:
    get:
      summary: Get contra by account no
      operationId: getContraByAccountNo
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
        - name: marketCode
          in: query
          description: market Code
          required: false
          schema:
            type: string
        - name: pageSize
          in: query
          description: page size
          required: false
          schema:
            type: number
            format: int32
        - name: pageIndex
          in: query
          description: page index
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  contra:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contra'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /contra/{accountNo}/details/{statementNo}:
    get:
      summary: Get contra details by account no
      operationId: getContraDetailByAccountNo
      parameters:
        - name: accountNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '0000001'
        - name: statementNo
          in: path
          description: Account Number
          required: true
          schema:
            type: string
            example: '2503984'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  contracts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contra'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    OutStandingContract:
      type: object
      description: account summary 
      properties:
        currency:
         type: string
        value:
         type: number
    AccountSummary:
      type: object
      description: account summary 
      properties:
        clientName:
          type: string
        productType:
          type: string
        accoutNumber:
          type: string
        accountType:
          type: string
        outstandingContracts:
          type: array
          items:
            $ref: '#/components/schemas/OutStandingContract'
    TrustBalance:
      type: object
      properties:
        currency:
          type: string
        balance:
          type: number
        lastUpdatedOn:
          type: string
          format: date-time
    TrustBalances:
      type: object
      properties:
        accountNo:
          type: string
        balances:
          type: array
          items:
            $ref: '#/components/schemas/TrustBalance'
    Custody:
      type: object
      properties:
        traderCode:
          type: string
        marketCode:
          type: string
        securityCode:
          type: string
        securityName:
          type: string
        availBalance:
          type: number
        freeBalance:
          type: number
        earmarkBalance:
          type: number
        lastUpdatedOn:
          type: string
          format: date-time
    CollateralFinancing:
     type: object
     properties:
        accountNo:
          type: string
        traderCode:
          type: string
        creditLimit:
          type: number
        ledgerBalance:
          type: number
        ytdInterest:
          type: number
        totalFinanced:
          type: number
        totalCollateral:
          type: number
        availableFinancing:
          type: number
        margin:
          type: number
        lastUpdatedOn:
          type: string
          format: date-time
    CollateralFinancingDetail:
      type: object
      properties:
        accountNo:
          type: string
        securityCode:
          type: string
        securityName:
          type: string
        quantity:
          type: number
        outstandingBuy:
          type: number
        outstandingSell:
          type: number
        balance:
          type: number
        lastDonePrice:
          type: number
        marketValue:
          type: number
        lastUpdatedOn:
          type: string
          format: date-time
    Contract:
      type: object
      properties:
        accountNo:
          type: string
        traderCode:
          type: string
        tradeDate:
          type: string
        contractNo:
          type: string
        type:
          type: string
        securityName:
          type: string
        tradedCurrency:
          type: string
        price:
          type: number
        quantity:
          type: number
        settlementCurrency:
          type: string
        netAmount: 
          type: number
        settlementDueDate:
          type: string
        channel:
          type: string
        remark:
          type: string
        marketCode:
          type: string
        baseNetAmt:
          type: number
        lastUpdatedOn:
          type: string
          format: date-time
    Contra:
      type: object
      properties:
        accountNo:
          type: string
        traderCode:
          type: string
        statementDate:
          type: string
        statementNo:
          type: string
        securityName:
          type: string
        type:
          type: string
        settlementCurrency:
          type: string
        settlementNetAmount:
          type: number
        marketCode:
          type: string
        baseNetAmt:
          type: number
        lastUpdatedOn:
          type: string
          format: date-time
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT