openapi: 3.0.4
info:
  title: iTrade API - Subscription API
  description: |-
    Subscription API
  version: 0.0.1
servers:
  - url: http://localhost:8080/portal/sso/api/v1
paths:
  /token:
    post:
      summary: Get Token by Code
      operationId: getAccessToken
      requestBody:
        description: SSO Code
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /token/refresh:
    post:
      summary: Get Token by Refresh Token
      operationId: getAccessTokenByRefresh
      requestBody:
        description: Refresh TOken
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /token/info:
    get:
      summary: Get Token Information from Claims
      operationId: getTokenInformation
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenInfoResponse'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    TokenRequest:
      type: object
      description: Subscription
      properties:
        sso:
          type: string
    RefreshTokenRequest:
      type: object
      description: Subscription
      properties:
        refresh:
          type: string
    TokenResponse:
      type: object
      description: Subscription
      properties:
        expires_in:
          type: string
        id_token:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
    TokenInfoResponse:
      type: object
      description: Subscription
      properties:
        systemId:
          type: string
        sessionId:
          type: string
        accounts:
          type: array
          items:
            type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT