openapi: 3.0.4
info:
  title: iTrade API - Subscription API
  description: |-
    Product Subscription & Market Data Subscription API
  version: 0.0.1
servers:
  - url: http://localhost:8080/portal/subscription/api/v1
paths:
  /subscription:
    get:
      summary: Get Subscription
      operationId: getSubscription
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref:  '#/components/schemas/Subscription'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /userSubscription:
    get:
      summary: Get User Subscription
      operationId: getUserSubscription
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userSubscription'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /product/{productType}:
    get:
      summary: Get Product Subscription by Product Type
      operationId: getProductSubs
      parameters:
        - name: productType
          in: path
          description: Possible  value (IPO, IOP, AI)
          required: true
          schema:
            type: string
            example: 'IPO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/productSubscription'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /product/details/{productCode}:
    get:
      summary: Get Product Subscription Detail
      operationId: getProductSubsDetail
      parameters:
        - name: productCode
          in: path
          required: true
          schema:
            type: string
            example: '0fd8dc31264d4dd68f4f93a3fe4b750c'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productSubscriptionDetail'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /product/mySubscription:
    get:
      summary: Get User product Subscription List
      operationId: getUserProductSubscription
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userProductSubscription'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    post:
      summary: Submit user product subscription
      operationId: SubmitUserProductSubscription
      requestBody:
        description: Product Submission Data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/submitProductSubscription'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productUserSubscriptionDetail'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /product/mySubscription/{subscriptionId}:
    get:
      summary: Get User Product Subscription Detail
      operationId: getUserProductSubscriptionDetail
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
            example: 'ETF-202305-00002'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productUserSubscriptionDetail'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Subscription:
      type: object
      description: Subscription
      properties:
        id:
          type: string
        category:
          type: string
        description:
          type: string
        amount:
          type: number
        needDeclaration:
          type: boolean
    userSubscription:
      type: object
      description: User Subscription
      properties:
        subscriptionId:
          type: string
        category:
          type: string
        description:
          type: string
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        paymentStatus:
          type: string
        allowRenew:
          type: boolean
    productSubscription:
      type: object
      description: Product Subscription
      properties:
        productCode:
          type: string
        productName:
          type: string
        productType:
          type: string
        stockCode:
          type: string
        exchangeCode:
          type: string
        currency:
          type: string
        issuePrice:
          type: number
        minQty:
          type: number
        startTime:
          type: string
          format: date
        endTime:
          type: string
          format: date
        isSubscribed:
          type: boolean
    submitProductSubscription:
      type: object
      description: Product Subscription
      properties:
        productCode:
          type: string
        accountNo:
          type: string
        totalUnit:
          type: string
        paymentCurrency:
          type: string
        paymentMode:
          type: string
    userProductSubscription:
      type: object
      description: Product Subscription
      properties:
        subscriptionId:
          type: string
        productCode:
          type: string
        productName:
          type: string
        productType:
          type: string
        stockCode:
          type: string
        exchangeCode:
          type: string
        currency:
          type: string
        issuePrice:
          type: number
        appliedQty:
          type: number
        allocateddQty:
          type: number
        endTime:
          type: string
          format: date
    productUserSubscriptionDetail:
      type: object
      description: Product Subscription
      properties:
        subscriptionId:
          type: string
        productCode:
          type: string
        productName:
          type: string
        productType:
          type: string
        stockCode:
          type: string
        exchangeCode:
          type: string
        noteGenerateDate:
          type: string
          format: date
        clientName:
          type: string
        accountNo:
          type: string
        taxNoteNo:
          type: string
        applicationDate:
          type: string
          format: date
        paymentDueDate:
          type: string
          format: date
        amountPayable:
          type: string
          format: number
        paymentCurrency:
          type: string
        baseCurrency:
          type: string
        totalUnit:
          type: string
          format: number
        issuePrice:
          type: number
        grossProceed:
          type: number
        commission:
          type: number
        adminFee:
          type: number
        gstAmount:
          type: number
        gstPct:
          type: number
        conversionRate:
          type: number
    productSubscriptionDetail:
      type: object
      description: Product Subscription
      properties:
        productCode:
          type: string
        productName:
          type: string
        productType:
          type: string
        stockCode:
          type: string
        exchangeCode:
          type: string
        issuePrice:
          type: number
        minQty:
          type: number
        incrementQty:
          type: number
        startTime:
          type: string
          format: dateTime
        endTime:
          type: string
          format: dateTime
        paymentDate:
          type: string
          format: date
        listingDate:
          type: string
          format: date
        baseCurrency:
          type: string
        tradingCurrency:
          type: string
        paymentMode:
          type: string
        excludedInvestment:
          type: string
        bannerUrl:
          type: string
        content1:
          type: string
        content2:
          type: string
          description: in JSON format, please check with Mya on the display
        additionalInfo:
          type: string
          description: in JSON format, please check with Mya on the display
        refDocs:
          type: string
          description: in JSON format, please check with Mya on the display
        tncUrl:
          type: string
        brokerageFee:
          type: number
        minBrokerageFee:
          type: number
        transferFee:
          type: number
        managementFee:
          type: number
        conversionRate:
          type: number
        gst:
          type: number
        minPrice:
          type: number
        maxPrice:
          type: number
        aiOnly:
          type: boolean
        paymentAfterAllocation:
          type: boolean
        allocationDate:
          type: string
          format: date
        acknowledgementDate:
          type: string
          format: date
        issuePriceStatus:
          type: boolean
        allocationStatus:
          type: boolean
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT