openapi: 3.0.4
info:
  title: iTrade API - Notification API
  description: |-
    Notificatoin API
  version: 0.0.1
servers:
  - url: http://localhost:8080/portal/notification/api/v1
paths:
  /list:
    get:
      summary: Get List Of user Notification
      operationId: getNotification
      parameters:
        - name: pageSize
          in: query
          description: page size (default = 10)
          required: false
          schema:
            type: number
            format: int32
        - name: pageIndex
          in: query
          description: page index (default = 0)
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: int32
                  notifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/notification'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /latest:
    get:
      summary: Get latest user notification
      operationId: getLatestNotification
      parameters:
        - name: pastMins
          in: query
          description: past minutes (default = 5)
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/notification'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /markAsRead:
    post:
      summary: Mark user Notification as Read
      operationId: updateMarkAsRead
      requestBody:
        description: SIP Submission Data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/idList'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarkAsReadResponse'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
  /admin/email/send:
    post:
      summary: Send email notification
      operationId: sendEmailNotification
      requestBody:
        description: email notification
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emailNotification'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarkAsReadResponse'
        '400':
          description: Invalid Request
        '404':
          description: No Accounts Linked 
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    notification:
      type: object
      description: Subscription
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        category:
          type: string
        status:
          type: string
          description: N = new, R = read
        createdOn:
          type: string
          format: date-time
    idList:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
    MarkAsReadResponse:
      type: object
      properties:
        isSuccess:
          type: boolean
    emailNotification:
      type: object
      description: Email Notification
      properties:
        triggerPoint:
          type: string
        toAddress:
          type: string
        params:
          $ref: '#/components/schemas/emailNotificationParam'
    emailNotificationParam:
      type: object
      description: Email Notification Content Parameters
      properties:
        name:
          type: string
        userId:
          type: string
        nric:
          type: string
        homeNo:
          type: string
        officeNo:
          type: string
        mobileNo:
          type: string
        email:
          type: string
        bmessage:
          type: string
        smessage:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT